import turtle
turtle.pensize(3)
turtle.penup()
turtle.goto(-200,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color('red','blue')
##turtle.circle(40)
turtle.circle(40,steps = 4)
turtle.end_fill()


turtle.penup()
turtle.goto(-100,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color('green','purple')
##turtle.circle(40)
turtle.circle(40,steps = 3)
turtle.end_fill()

turtle.penup()
turtle.goto(0,-50)
turtle.pendown()
turtle.begin_fill()
turtle.color('red')
turtle.circle(40)
##turtle.circle(40,steps = 4)
turtle.end_fill()


turtle.color('black')
turtle.penup()
turtle.goto(-50,50)
turtle.pendown()
turtle.write(('Cool Colorful Shapes'),font = ('Times',18,'bold'))
turtle.hideturtle()
turtle.done()
